{% set name = "veloxchem" %}
{% set gitsha = "8513267a275d8f3feca17e9d24741ceeaedaa6b6" %}
{% set sha256 = "8c59d7acdb429d873ccaeab07d138a1d28be32c9f94e948cfbe19f4e9474db54" %}
{% set version = "1.0" %}
{% set pre = "rc4" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}{{ pre }}"

source:
  url: https://github.com/VeloxChem/VeloxChem/archive/{{ gitsha }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  entry_points:
    - vlx=veloxchem.main:main

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx or win]
    - ninja
  host:
    - pybind11
    - python
    - pybind11-abi =4
    - numpy
    - eigen
    - libboost-headers
    - libxc-c >=7.0.0
  run:
    - psutil
    - geometric
    - h5py
    - python
    - mpi4py
    - numpy >=2
  run_constrained:
    # NOTE gets past a TypeError when setting verbosity
    - xtb >=6.7  # [(linux or (osx and x86_64)) and py==310]
    # NOTE newer builds of xtb fail the tests
    - xtb 6.7.1 *_3  # [win]

test:
  requires:
    - pytest
    - dftd4-python
    - xtb-python
    - pip
    - scipy
    - openmm
    - matplotlib
    - rdkit
    - pymbar
    - mdanalysis
    - binutils  # [win]
  source_files:
    - tests/
  imports:
    - veloxchem
  commands:
    - pip check
    # verify we can execute the CLI
    - vlx --version
    - vlx --help
    # inspect linkage
    - ldd -v $SP_DIR/veloxchem/veloxchemlib*.so  # [linux]
    - otool -L $SP_DIR/veloxchem/veloxchemlib*.so  # [osx]
    - objdump.exe -p %SP_DIR%\\veloxchem\\veloxchemlib.*.pyd | findstr /i "dll"  # [win]
    # run integration tests on unix-like systems
    # for now we only run selected tests on osx-64 and osx-arm64 due to time and resources
    - export OMP_NUM_THREADS=$CPU_COUNT  # [unix]
    - mpiexec -n 1 $PYTHON -m pytest -ra --capture=no --log-cli-level=INFO -m "not timeconsuming"  # [linux]
    - mpiexec -n 1 $PYTHON -m pytest -ra --capture=no --log-cli-level=INFO -m "not timeconsuming"  # [osx and arm64]
    - mpiexec -n 1 $PYTHON -m pytest -ra --capture=no --log-cli-level=INFO -m "not timeconsuming and not solvers"  # [osx and x86_64]
    - export MPI_NUM_PROCS=2  # [unix]
    - export OMP_NUM_THREADS=$(($CPU_COUNT/$MPI_NUM_PROCS))  # [unix]
    - mpiexec -n $MPI_NUM_PROCS $PYTHON -m pytest -ra --capture=no --log-cli-level=INFO -m solvers  # [linux]
    - mpiexec -n $MPI_NUM_PROCS $PYTHON -m pytest -ra --capture=no --log-cli-level=INFO -m solvers -k "TestScf or TestGrad or TestRI or TestCPP or TestRPA"  # [osx and arm64]
    # run integration tests on windows
    - set OMP_NUM_THREADS=%CPU_COUNT%  # [win]
    - mpiexec -n 1 %PYTHON% -m pytest -ra --capture=no --log-cli-level=INFO -m "not timeconsuming"  # [win]
    - set MPI_NUM_PROCS=2  # [win]
    - set /A OMP_NUM_THREADS="%CPU_COUNT%/%MPI_NUM_PROCS%"  # [win]
    - mpiexec -n %MPI_NUM_PROCS% %PYTHON% -m pytest -ra --capture=no --log-cli-level=INFO -m solvers  # [win]

about:
  home: https://veloxchem.org
  dev_url: https://github.com/VeloxChem/VeloxChem
  doc_url: https://veloxchem.org
  license: BSD-3-Clause
  license_url: https://opensource.org/license/BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE-THIRD-PARTY
  license_family: BSD
  summary: A Python-based, open source quantum chemistry program package

extra:
  recipe-maintainers:
    - robertodr
